name: Android CI
on:
  push:
    branches:
      - main
      - final
  pull_request:
    branches:
      - main
      - final

env:
  java_version: 11

jobs:
  package:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Run Lint
        run: ./gradlew ktlintCheck  --build-cache --stacktrace

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
